[pytest]
python_files = test_*.py *_test.py [0-9][0-9].*.py
pythonpath = .
addopts = --self-contained-html --import-mode=importlib
markers =
    priority1: high-priority tests to run across smoke/sanity/regression suites
    data_match: custom marker for data validation tests
